### ISSUE TITLE
Cucumber tests randomly failing

### ISSUE THREAD

**Issue by wioux** [EFForg/action-center-platform#278] opened 2017-01-19 20:08 UTC
- Travis build occasionally fails with "no output received in 10m" while running cucumber
- `features/admin/action_pages/image_gallery.feature:14` fails intermittently

**Comment by wioux** [comment] 2017-03-27 22:35
`features/admin/action_pages/image_gallery.feature:6` tends to hang.

**Comment by vbrown608** [comment] 2017-09-12 18:49
This is caused by javascript animations and css transitions. I was able to solve it by triggering a click event on submit buttons that appear after an animation rather than haivng capybara actually press the submit button. If it comes up a lot, another approach is to disable animations during test runs, ex:

- By injecting javascript into Capybara runs: https://gist.github.com/andyjbas/9962218
- By adding it to templates based on the environment: https://gist.github.com/jwood/90e7bf6873774055b169

I'm going to close this for now, we can do one of those if this continues to cause problems.

**Closed by vbrown608** 2017-09-12 18:49 UTC
